baseurl = "https://Halbtonfoto.de"
title = "HalbtonFoto"
author = "HalbtonFoto"
paginate = 3
theme = "arabica"

[params]
    description = "Blog"
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"
#    twitter = "example"
#    facebook = "example"
